toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - image
  - link
toolbar:
  - formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat